[package]
name = "rust_bert"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
rust-bert = "0.23"
ndarray = "0.15"
anyhow = "1.0"
# Force newer tch version
tch = "0.20.0"
